In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('fra_cleaned_with_images.csv', encoding='latin-1', on_bad_lines='skip', delimiter=';')
df.head()

,ï»¿url,perfume,brand,country,gender,rating value,rating count,year,top,middle,base,perfumer1,perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,mainaccord5,image_url
0,https://www.fragrantica.com/perfume/xerjoff/ac...,accento-overdose-pride-edition,xerjoff,Italy,unisex,1.42,201,2022.0,"fruity notes, aldehydes, green notes","bulgarian rose, egyptian jasmine, lily-of-the-...","eucalyptus, pine",unknown,NaN,rose,woody,fruity,aromatic,floral,https://fimgs.net/mdimg/perfume-thumbs/375x500...
1,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2024,jean-paul-gaultier,France,women,1.86,70,2024.0,"yuzu, citruses","orange blossom, neroli","musk, blonde woods",unknown,NaN,citrus,white floral,sweet,fresh,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
2,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2023,jean-paul-gaultier,France,unisex,1.91,285,2023.0,"blood orange, yuzu","neroli, orange blossom","musk, white woods",natalie gracia-cetto,quentin bisch,citrus,white floral,sweet,fresh spicy,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
3,https://www.fragrantica.com/perfume/bruno-bana...,pride-edition-man,bruno-banani,Germany,men,1.92,59,2019.0,"guarana, grapefruit, red apple","walnut, lavender, guava","vetiver, benzoin, amber",unknown,NaN,fruity,nutty,woody,tropical,NaN,https://fimgs.net/mdimg/perfume-thumbs/375x500...
4,https://www.fragrantica.com/perfume/jean-paul-...,le-male-pride-collector,jean-paul-gaultier,France,men,1.93,632,2020.0,"mint, lavender, cardamom, artemisia, bergamot","caraway, cinnamon, orange blossom","vanilla, sandalwood, amber, cedar, tonka bean",francis kurkdjian,NaN,aromatic,warm spicy,fresh spicy,cinnamon,vanilla,https://fimgs.net/mdimg/perfume-thumbs/375x500...

In [3]:
df.rename(columns={'ï»¿url': 'url'}, inplace=True)
df.head()

,url,perfume,brand,country,gender,rating value,rating count,year,top,middle,base,perfumer1,perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,mainaccord5,image_url
0,https://www.fragrantica.com/perfume/xerjoff/ac...,accento-overdose-pride-edition,xerjoff,Italy,unisex,1.42,201,2022.0,"fruity notes, aldehydes, green notes","bulgarian rose, egyptian jasmine, lily-of-the-...","eucalyptus, pine",unknown,NaN,rose,woody,fruity,aromatic,floral,https://fimgs.net/mdimg/perfume-thumbs/375x500...
1,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2024,jean-paul-gaultier,France,women,1.86,70,2024.0,"yuzu, citruses","orange blossom, neroli","musk, blonde woods",unknown,NaN,citrus,white floral,sweet,fresh,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
2,https://www.fragrantica.com/perfume/jean-paul-...,classique-pride-2023,jean-paul-gaultier,France,unisex,1.91,285,2023.0,"blood orange, yuzu","neroli, orange blossom","musk, white woods",natalie gracia-cetto,quentin bisch,citrus,white floral,sweet,fresh spicy,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
3,https://www.fragrantica.com/perfume/bruno-bana...,pride-edition-man,bruno-banani,Germany,men,1.92,59,2019.0,"guarana, grapefruit, red apple","walnut, lavender, guava","vetiver, benzoin, amber",unknown,NaN,fruity,nutty,woody,tropical,NaN,https://fimgs.net/mdimg/perfume-thumbs/375x500...
4,https://www.fragrantica.com/perfume/jean-paul-...,le-male-pride-collector,jean-paul-gaultier,France,men,1.93,632,2020.0,"mint, lavender, cardamom, artemisia, bergamot","caraway, cinnamon, orange blossom","vanilla, sandalwood, amber, cedar, tonka bean",francis kurkdjian,NaN,aromatic,warm spicy,fresh spicy,cinnamon,vanilla,https://fimgs.net/mdimg/perfume-thumbs/375x500...

In [4]:
print(df.columns)

Index(['url', 'perfume', 'brand', 'country', 'gender', 'rating value',
       'rating count', 'year', 'top', 'middle', 'base', 'perfumer1',
       'perfumer2', 'mainaccord1', 'mainaccord2', 'mainaccord3', 'mainaccord4',
       'mainaccord5', 'image_url'],
      dtype='object')

In [5]:
columns_to_replace = ["perfume", "brand", "top", "middle", "base"]
df[columns_to_replace] = df[columns_to_replace].replace("-", " ", regex=True)

In [7]:
df.head()

,url,perfume,brand,country,gender,rating value,rating count,year,top,middle,base,perfumer1,perfumer2,mainaccord1,mainaccord2,mainaccord3,mainaccord4,mainaccord5,image_url
0,https://www.fragrantica.com/perfume/xerjoff/ac...,accento overdose pride edition,xerjoff,Italy,unisex,1.42,201,2022.0,"fruity notes, aldehydes, green notes","bulgarian rose, egyptian jasmine, lily of the ...","eucalyptus, pine",unknown,NaN,rose,woody,fruity,aromatic,floral,https://fimgs.net/mdimg/perfume-thumbs/375x500...
1,https://www.fragrantica.com/perfume/jean-paul-...,classique pride 2024,jean paul gaultier,France,women,1.86,70,2024.0,"yuzu, citruses","orange blossom, neroli","musk, blonde woods",unknown,NaN,citrus,white floral,sweet,fresh,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
2,https://www.fragrantica.com/perfume/jean-paul-...,classique pride 2023,jean paul gaultier,France,unisex,1.91,285,2023.0,"blood orange, yuzu","neroli, orange blossom","musk, white woods",natalie gracia-cetto,quentin bisch,citrus,white floral,sweet,fresh spicy,musky,https://fimgs.net/mdimg/perfume-thumbs/375x500...
3,https://www.fragrantica.com/perfume/bruno-bana...,pride edition man,bruno banani,Germany,men,1.92,59,2019.0,"guarana, grapefruit, red apple","walnut, lavender, guava","vetiver, benzoin, amber",unknown,NaN,fruity,nutty,woody,tropical,NaN,https://fimgs.net/mdimg/perfume-thumbs/375x500...
4,https://www.fragrantica.com/perfume/jean-paul-...,le male pride collector,jean paul gaultier,France,men,1.93,632,2020.0,"mint, lavender, cardamom, artemisia, bergamot","caraway, cinnamon, orange blossom","vanilla, sandalwood, amber, cedar, tonka bean",francis kurkdjian,NaN,aromatic,warm spicy,fresh spicy,cinnamon,vanilla,https://fimgs.net/mdimg/perfume-thumbs/375x500...

In [12]:
def to_set(value):
    if value is None:
        return set()

    text = str(value).strip().lower()
    if not text or text == "nan":
        return set()

    return {item.strip() for item in text.split(",") if item.strip()}

ACCORD_COLUMNS = ["mainaccord1", "mainaccord2", "mainaccord3", "mainaccord4", "mainaccord5"]

def accords_from_row(row):
    accords = set()
    for col in ACCORD_COLUMNS:
        value = row[col]
        if value is not None:
            text = str(value).strip().lower()
            if text and text != "nan":
                accords.add(text)
    return accords

def normalize_gender(value):
    text = str(value).strip().lower()

    if text in {"male", "man", "men", "masculine"}:
        return "male"
    if text in {"female", "woman", "women", "feminine"}:
        return "female"
    if text in {"unisex", "shared"}:
        return "unisex"

    return "unknown"

perfumes = []

for idx, row in df.iterrows():
    perfumes.append({
        "id": idx,
        "perfume": row["perfume"],
        "brand": row["brand"],
        "top": to_set(row["top"]),
        "middle": to_set(row["middle"]),
        "base": to_set(row["base"]),
        "accords": accords_from_row(row),
        "gender": normalize_gender(row["gender"]),
        "rating_value": float(row["rating value"]) if str(row["rating value"]) != "nan" else 0.0,
        "rating_count": int(row["rating count"]) if str(row["rating count"]) != "nan" else 0,
        "url": row["url"],
        "image_url": row["image_url"]
    })

In [13]:
perfumes[1]

{'id': 1,
 'perfume': 'classique pride 2024',
 'brand': 'jean paul gaultier',
 'top': {'citruses', 'yuzu'},
 'middle': {'neroli', 'orange blossom'},
 'base': {'blonde woods', 'musk'},
 'accords': {'citrus', 'fresh', 'musky', 'sweet', 'white floral'},
 'gender': 'female',
 'rating_value': 1.86,
 'rating_count': 70,
 'url': 'https://www.fragrantica.com/perfume/jean-paul-gaultier/classique-pride-2024-90394.html',
 'image_url': 'https://fimgs.net/mdimg/perfume-thumbs/375x500.90394.jpg'}

In [10]:
#Build vocabularies from perfume data

all_notes = set()
all_accords = set()

for p in perfumes:
    all_notes.update(p["top"])
    all_notes.update(p["middle"])
    all_notes.update(p["base"])
    all_accords.update(p["accords"])

all_notes = sorted(all_notes)
all_accords = sorted(all_accords)

In [11]:
print(len(all_notes))
print(len(all_accords))

print(all_notes[:20])
print(all_accords[:20])

1669
84
['absinthe', 'acai berry', 'accord eudoraâ®', 'acerola', 'acerola blossom', 'acetylfuran', 'acã¡cia', 'african freesia petals', 'african geranium', 'african ginger', 'african orange flower', 'african violet', 'agarwood', 'agarwood (oud)', 'agave', 'agave nectar', 'aglaia', 'akigalawood', 'aldehydes', 'algae']
['alcohol', 'aldehydic', 'almond', 'amber', 'animalic', 'anis', 'aquatic', 'aromatic', 'asphault', 'balsamic', 'beeswax', 'bitter', 'brown scotch tape', 'cacao', 'camphor', 'cannabis', 'caramel', 'champagne', 'cherry', 'chocolate']

In [15]:
import json

# Convert sets to lists for JSON serialization
perfumes_json = []
for p in perfumes:
    p_copy = p.copy()
    p_copy['top'] = list(p_copy['top'])
    p_copy['middle'] = list(p_copy['middle'])
    p_copy['base'] = list(p_copy['base'])
    p_copy['accords'] = list(p_copy['accords'])
    perfumes_json.append(p_copy)

with open('perfumes.json', 'w') as f:
    json.dump(perfumes_json, f, indent=2)